defmodule Interruptus.Command do
  @moduledoc """
  Commandex-compatible helpers for workflow command structs.

  Workflow modules generated by `Interruptus.Workflow` produce a command struct with
  `params`, `data`, `errors`, `halted`, and `success` fields. Use these helpers inside
  pipeline stage functions to update state and control execution flow.

  Stage functions should return the updated command struct, `{:suspend, reason, metadata}`,
  or call `halt/2` to stop forward progress.
  """

  @typedoc "Workflow command struct."
  @type t :: struct()

  @doc """
  Sets a data field on the command struct.

  Data fields are declared with `data/1` in the workflow module and persist across
  checkpoints when JSON-serializable.

  ## Arguments

    * `command` - workflow command struct
    * `key` - atom key for the data field
    * `val` - value to store

  ## Returns

    * Updated command struct with `data[key]` set to `val`

  ## Examples

      iex> cmd = %Interruptus.Test.Support.Workflows.Simple{
      ...>   data: %{result: nil},
      ...>   params: %{value: 1},
      ...>   errors: %{},
      ...>   halted: false,
      ...>   success: false,
      ...>   pipelines: []
      ...> }
      iex> updated = Interruptus.Command.put_data(cmd, :result, 42)
      iex> updated.data.result
      42
  """
  @spec put_data(t(), atom(), any()) :: t()
  def put_data(%{data: data} = command, key, val) do
    %{command | data: Map.put(data, key, val)}
  end

  @doc """
  Sets an error for the given key on the command struct.

  ## Arguments

    * `command` - workflow command struct
    * `key` - error key (atom or string)
    * `val` - error value

  ## Returns

    * Updated command struct with `errors[key]` set to `val`

  ## Examples

      iex> cmd = %Interruptus.Test.Support.Workflows.Simple{
      ...>   data: %{result: nil},
      ...>   params: %{value: 1},
      ...>   errors: %{},
      ...>   halted: false,
      ...>   success: false,
      ...>   pipelines: []
      ...> }
      iex> updated = Interruptus.Command.put_error(cmd, :amount, "invalid")
      iex> updated.errors[:amount]
      "invalid"
  """
  @spec put_error(t(), any(), any()) :: t()
  def put_error(%{errors: errors} = command, key, val) do
    %{command | errors: Map.put(errors, key, val)}
  end

  @doc """
  Halts pipeline execution for the current segment.

  Sets `halted: true` on the command. The engine treats a halted command as a
  segment failure and applies the workflow restart policy.

  ## Arguments

    * `command` - workflow command struct

  ## Options

    * `:success` - when `true`, marks `success: true` despite halting (default `false`)

  ## Returns

    * Updated command struct with `halted: true`

  ## Examples

      iex> cmd = %Interruptus.Test.Support.Workflows.Simple{
      ...>   data: %{result: nil},
      ...>   params: %{value: 1},
      ...>   errors: %{},
      ...>   halted: false,
      ...>   success: false,
      ...>   pipelines: []
      ...> }
      iex> halted = Interruptus.Command.halt(cmd)
      iex> halted.halted
      true
      iex> halted.success
      false
  """
  @spec halt(t(), keyword()) :: t()
  def halt(command, opts \\ []) do
    success = Keyword.get(opts, :success, false)
    %{command | halted: true, success: success}
  end

  @doc """
  Marks the command as successful when execution was not halted.

  Called by the engine when all segments complete without halt or error.

  ## Arguments

    * `command` - workflow command struct

  ## Returns

    * Command with `success: true` when `halted` is `false`
    * Unchanged command when already halted

  ## Examples

      iex> cmd = %Interruptus.Test.Support.Workflows.Simple{
      ...>   data: %{result: nil},
      ...>   params: %{value: 1},
      ...>   errors: %{},
      ...>   halted: false,
      ...>   success: false,
      ...>   pipelines: []
      ...> }
      iex> Interruptus.Command.maybe_mark_successful(cmd).success
      true
      iex> halted = Interruptus.Command.halt(cmd)
      iex> Interruptus.Command.maybe_mark_successful(halted).success
      false
  """
  @spec maybe_mark_successful(t()) :: t()
  def maybe_mark_successful(%{halted: false} = command), do: %{command | success: true}
  def maybe_mark_successful(command), do: command

  @doc """
  Merges runtime parameters into the command struct defaults.

  Accepts a keyword list or map. Map keys may be atoms or strings; string keys
  matching atom param names are accepted.

  ## Arguments

    * `struct` - command struct with default `params` from the workflow definition
    * `params` - keyword list or map of parameter values

  ## Returns

    * Command struct with `params` populated from defaults and overrides

  ## Examples

      iex> struct = %Interruptus.Test.Support.Workflows.Simple{
      ...>   params: %{value: nil},
      ...>   data: %{result: nil},
      ...>   errors: %{},
      ...>   halted: false,
      ...>   success: false,
      ...>   pipelines: []
      ...> }
      iex> parsed = Interruptus.Command.parse_params(struct, value: 10)
      iex> parsed.params.value
      10
  """
  @spec parse_params(t(), map() | Keyword.t()) :: t()
  def parse_params(%{params: defaults} = struct, params) when is_list(params) do
    params =
      for {key, _} <- defaults, into: %{}, do: {key, Keyword.get(params, key, defaults[key])}

    %{struct | params: params}
  end

  def parse_params(%{params: defaults} = struct, %{} = params) do
    params =
      for {key, _} <- defaults, into: %{}, do: {key, get_param(params, key, defaults[key])}

    %{struct | params: params}
  end

  @doc """
  Invokes a pipeline stage function against the command.

  Resolves the stage target in several forms:

    * atom — calls `workflow_module.name(command, params, data)`
    * `{module, function}` — calls `module.function(command, params, data)`
    * `{module, function, extra_args}` — appends `extra_args` to the argument list
    * `fun/1` — calls `fun.(command)`
    * `fun/3` — calls `fun.(command, params, data)`

  ## Arguments

    * `command` - workflow command struct (must include `params` and `data`)
    * `name` - stage reference as atom, MFA tuple, or function

  ## Returns

    * Updated command struct when the stage returns a map
    * `{:suspend, reason, metadata}` when the stage requests voluntary suspension

  ## Raises

    * `UndefinedFunctionError` - when the resolved MFA does not exist
    * `ArgumentError` - when the stage arity does not match
  """
  @spec apply_fun(t(), any()) :: t() | {:suspend, term(), map()}
  def apply_fun(%mod{params: params, data: data} = command, name) when is_atom(name) do
    apply(mod, name, [command, params, data])
  end

  def apply_fun(command, fun) when is_function(fun, 1), do: fun.(command)

  def apply_fun(%{params: params, data: data} = command, fun) when is_function(fun, 3) do
    fun.(command, params, data)
  end

  def apply_fun(%{params: params, data: data} = command, {m, f}) do
    apply(m, f, [command, params, data])
  end

  def apply_fun(%{params: params, data: data} = command, {m, f, a}) do
    apply(m, f, [command, params, data] ++ a)
  end

  @spec get_param(map(), atom(), any()) :: any()
  defp get_param(params, key, default) do
    case Map.get(params, key) do
      nil -> Map.get(params, to_string(key), default)
      val -> val
    end
  end
end
